### ISSUE TITLE
Blank page on IE 11: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by asosso** [authelia/authelia#1471]
I'm unable to load the login page from IE 11 from the latest Authelia release v4.23.2
The page is blank.

Here the error:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
my.authelia.url
HTML1300: Navigation occurred.
my.authelia.url
TypeError: Object doesn't support property or method 'assign'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'assign'",
      message: "Object doesn't support property or method 'assign'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'assign'
   at v (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:77590)
   at It (https://my.authelia.url/static/js/main.fc9a15fb.chunk.js:1:22447)
   at qn (https://my.authelia.url/static/js/main.fc9a15fb.chunk.js:1:48424)
   at Ji (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:215039)
   at kl (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:261274)
   at yu (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:254114)
   at mu (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:254042)
   at lu (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:251054)
   at nu (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:247815)
   at Hu (https://my.authelia.url/static/js/2.52b7d34d.chunk.js:2:268990)"
   }

SCRIPT438: Object doesn't support property or method 'assign'
2.52b7d34d.chunk.js (2,258988)
```

Probably IE 11 is not fully supported by React: https://reactjs.org/docs/javascript-environment-requirements.html

Is anyone else having this issue?

**Comment by nightah** [comment]
I don't personally use IE11 but since it's still on machine I gave it a try.

I received the same error as you, is there something that's stopping you from running a modern browser?

Given the EOS and EOL dates for IE11 I'm not sure that we will invest time in to supporting IE11.

**Comment by nightah** [comment]
Closing this as a `wont-fix` due to the following:

> Microsoft will end support for Internet Explorer 11 across its Microsoft 365 apps and services next year. In exactly a year, on August 17th, 2021, Internet Explorer 11 will no longer be supported for Microsoft's online services like Office 365, OneDrive, Outlook, and more.
