### ISSUE TITLE
Session to LDAP is not closed when queries fail.

### ISSUE THREAD

**Issue by SHSauler** [authelia/authelia#225]
Hi again! Thanks for your project!

This might be related to #58. Did this twice to check whether this is a real issue.

Steps to reproduce:

* LDAP query for user, which succeeds
* LDAP query for group, which fails with `problem 2001 (NO_OBJECT)`

Exactly after 15 mins of idling, the docker will crash with:

```
Error: read ECONNRESET
    at _errnoException (util.js:1021:11)
    at TCP.onread (net.js:608:25)
```

Full logs:
```
debug: LDAP: Bind user 'CN=querycount,OU=query,DC=somecorp,DC=corp'
debug: Computed users filter is cn=LOGINUSER
debug: LDAP: searching for user dn of LOGINUSER
debug: LDAP: retrieved user dn is CN=LOGINUSER,OU=users,DC=somecorp,DC=corp
debug: LDAP: Bind user 'CN=LOGINUSER,OU=users,DC=somecorp,DC=corp'
debug: LDAP: Unbind user 'CN=LOGINUSER,OU=users,DC=somecorp,DC=corp'
debug: LDAP: Bind user 'CN=querycount,OU=query,DC=somecorp,DC=corp'
debug: Computed users filter is cn=LOGINUSER
debug: LDAP: searching for user dn of LOGINUSER
debug: LDAP: retrieved user dn is CN=LOGINUSER,OU=users,DC=somecorp,DC=corp
debug: LDAP: emails of user 'LOGINUSER' are loginuser@somecorp.com
debug: Computed groups filter is (&(objectClass=user)(sAMAccountName=LOGINUSER)(memberOf=CN=SOMEGROUP,OU=groups,DC=somecorp,DC=corp))
error: date='Fri May 04 2018 15:02:54 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a6f6db25-0d6f-4b73-8482-196e94d4f578' sessionId='D3zfPcXRu5Q56HYTfFykzso-3YbL0ej9' ip='removed' message='Reply with error 200: 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
        'OU=groups,DC=somecorp,DC=corp'
'
debug: date='Fri May 04 2018 15:02:54 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a6f6db25-0d6f-4b73-8482-196e94d4f578' sessionId='D3zfPcXRu5Q56HYTfFykzso-3YbL0ej9' ip='removed' message='LdapSearchError: 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
        'OU=groups,DC=somecorp,DC=corp'

    at /usr/src/server/src/lib/ldap/LdapClient.js:37:43
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)'
```

**Comment by clems4ever** [comment]
Hello @SHSauler , I think your error might more be related to the actual error we can see in the logs: 
```

**Comment by SHSauler** [comment]
Yes, the `(NO_OBJECT)` is a problem on our side. But the `ECONNRESET` & crash bit comes 15 mins after the full log snippet above.

**Comment by clems4ever** [comment]
Ok, maybe there is a bug preventing the session from being closed when the search query fails. I'll have a look. Thanks for reporting.

**Comment by naggie** [comment]
I'm also seeing this, in particular when I have the LDAP configuration wrong.  As a workaround, I've updated my systemd configuration to restart authelia on crash after 3 seconds in case it is triggered.

**Comment by naggie** [comment]
Thanks, it seems to have stopped the errors!

**Comment by clems4ever** [comment]
Good!
