### ISSUE TITLE
Crash on refresh token : panic: interface conversion: fosite.Session is *openid.DefaultSession, not *model.OpenIDSession

### ISSUE THREAD

**Issue by andreas-berg** [authelia/authelia#3537]
## Bug Report
Fetching a new token (immediately) after succesful OIDC authentication/authorization causes authelia to crash in error:
`panic: interface conversion: fosite.Session is *openid.DefaultSession, not *model.OpenIDSession`

### Description

I'm trying to get OIDC to work from a next-auth.js-based application. 
Authentication and authorization works fine and when including scope "offline_access" I get the "refresh_token" as I should. 
After bugfix #3534 I now got as far as to systematically crashing the authelia-server in error:
panic: interface conversion: fosite.Session is *openid.DefaultSession, not *model.OpenIDSession

I'm refreshing/fetching a new token immediately after getting the access token from `/api/oidc/authorization`. 
This is the relevant code from my `[...nextauth].page.ts` , the await fetch(url ... causes the crash:

```
      ...
      const url = 'https://hubbb-authelia-192-168-12-159.traefik.me/api/oidc/token'
      const body = new URLSearchParams({
          client_id: '322b825471a545a811e0640435978e80',
          client_secret: '***',
          grant_type: 'refresh_token',
          refresh_token: token.refreshToken,
          scope: 'offline_access'
      })
      const response = await fetch(url, {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        method: 'POST',
        body
      })
      ....

```
This is my docker-compose.yml for authelia:
```
  authelia:
    # image: authelia/authelia
    image: authelia/authelia:PR3535
    container_name: authelia
    volumes:
      - ./docker/configs/authelia:/config
    networks:
      - bridged_network
    labels:
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
      - 'traefik.http.routers.authelia.rule=HostRegexp(`hubbb-authelia.traefik.me`,`hubbb-authelia-{dashed-ip:.*}.traefik.me`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.service=authelia-svc'
      - 'traefik.http.middlewares.authelia-mw.forwardauth.address=http://authelia:9091/api/verify?rd=https://hubbb-authelia.traefik.me'
      - 'traefik.http.middlewares.authelia-mw.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-mw.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=Europe/Helsinki
      - AUTHELIA_LOG_LEVEL=trace
      - AUTHELIA_STORAGE_POSTGRES_HOST=authelia-db
      - AUTHELIA_STORAGE_POSTGRES_DATABASE=authelia
      - AUTHELIA_STORAGE_POSTGRES_USERNAME=authelia
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD=***
      - AUTHELIA_SESSION_REDIS_HOST=authelia-redis
```
Authelia-server is setup with redis(separate docker-container) for sessions and postgresql(separate docker-container) for storage. Two OIDC clients configured, the one used by the next-app has the following conf:

```
      - id: 322b825471a545a811e0640435978e80
        description: Hubbb Webbb
        secret: ***
        sector_identifier: ''
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: ''
        audience: ['322b825471a545a811e0640435978e80']
        scopes:
          - openid
          - groups
          - email
          - profile
          - offline_access
        redirect_uris:
          - http://localhost:3000/api/auth/callback/authelia
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
          - id_token
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```

Finally, the authelia-trace-log (boot-authentication-authorization-refreshAttempt-crash):

```
authelia                  | time="2022-06-17T13:47:04+03:00" level=info msg="Authelia untagged-v4.35.6 (andreas-berg:master, effc878) is starting"
authelia                  | time="2022-06-17T13:47:04+03:00" level=info msg="Log severity set to trace"
authelia                  | time="2022-06-17T13:47:04+03:00" level=trace msg="Starting scan of directory  for certificates"
authelia                  | time="2022-06-17T13:47:04+03:00" level=trace msg="Finished scan of directory  for certificates"
authelia                  | time="2022-06-17T13:47:04+03:00" level=debug msg="Registering client 8044d085c3eb449309a035bffb51b1db with policy one_factor (1)"
authelia                  | time="2022-06-17T13:47:04+03:00" level=debug msg="Registering client 322b825471a545a811e0640435978e80 with policy one_factor (1)"
authelia                  | time="2022-06-17T13:47:04+03:00" level=info msg="Storage schema is being checked for updates"
authelia                  | time="2022-06-17T13:47:05+03:00" level=info msg="Storage schema is already up to date"
authelia                  | time="2022-06-17T13:47:05+03:00" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
authelia                  | time="2022-06-17T13:47:05+03:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
authelia                  | time="2022-06-17T13:47:21+03:00" level=trace msg="Request hit" method=GET path=/.well-known/openid-configuration remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:21+03:00" level=trace msg="Replied (status=200)" method=GET path=/.well-known/openid-configuration remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:21+03:00" level=trace msg="Request hit" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:21+03:00" level=debug msg="Authorization Request with id 'ba7f6bec-76f1-46cf-a5e4-61ec63ca3b0c' on client with id '322b825471a545a811e0640435978e80' is being processed" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:21+03:00" level=debug msg="Authorization Request with id 'ba7f6bec-76f1-46cf-a5e4-61ec63ca3b0c' on client with id '322b825471a545a811e0640435978e80' authentication level 'not_authenticated' is insufficient for client level 'one_factor'" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:21+03:00" level=debug msg="Authorization Request with id 'ba7f6bec-76f1-46cf-a5e4-61ec63ca3b0c' on client with id '322b825471a545a811e0640435978e80' is being redirected to 'https://hubbb-authelia-192-168-12-159.traefik.me'" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:21+03:00" level=trace msg="Replied (status=302)" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:22+03:00" level=trace msg="Request hit" method=GET path=/ remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:22+03:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:22+03:00" level=trace msg="Request hit" method=GET path=/static/css/index.0ebfbcc6.css remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:22+03:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.0ebfbcc6.css remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:22+03:00" level=trace msg="Request hit" method=GET path=/static/js/index.7dee0754.js remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:22+03:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.7dee0754.js remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:23+03:00" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:23+03:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:23+03:00" level=trace msg="Request hit" method=GET path=/locales/en-GB/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:23+03:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en-GB/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:24+03:00" level=trace msg="Request hit" method=GET path=/favicon.ico remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:24+03:00" level=trace msg="Replied (status=200)" method=GET path=/favicon.ico remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:24+03:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:24+03:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:27+03:00" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=debug msg="Mark 1FA authentication attempt made by user 'andreas'" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=debug msg="Successful 1FA authentication attempt made by user 'andreas'" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=trace msg="Profile details for user 'andreas' => groups: [admins Reader], emails [andreas.berg@iki.fi]" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=debug msg="Consent Session is being checked for pre-configuration with signature of client id '322b825471a545a811e0640435978e80' and subject '4a72128a-120c-493a-aa4e-c616c6dc80cb'" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=debug msg="Consent Session checked for pre-configuration with signature of client id '322b825471a545a811e0640435978e80' and subject '4a72128a-120c-493a-aa4e-c616c6dc80cb' did not find any results" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=trace msg="Timing Attack Delay successful: true, exec duration: 2106, avg execution duration: 1000, random delay ms: 8, total delay ms: 1008, actual delay ms: 1" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=trace msg="Request hit" method=GET path=/consent remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:29+03:00" level=trace msg="Replied (status=200)" method=GET path=/consent remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:30+03:00" level=trace msg="Request hit" method=GET path=/static/css/index.0ebfbcc6.css remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:30+03:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.0ebfbcc6.css remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:30+03:00" level=trace msg="Request hit" method=GET path=/static/js/index.7dee0754.js remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:30+03:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.7dee0754.js remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:31+03:00" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:31+03:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Request hit" method=GET path=/locales/en-GB/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en-GB/portal.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Request hit" method=GET path=/favicon.ico remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Replied (status=200)" method=GET path=/favicon.ico remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Request hit" method=GET path=/api/user/info remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Request hit" method=GET path=/api/oidc/consent remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:32+03:00" level=trace msg="Replied (status=200)" method=GET path=/api/oidc/consent remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:33+03:00" level=trace msg="Replied (status=200)" method=GET path=/api/user/info remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Request hit" method=POST path=/api/oidc/consent remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Replied (status=200)" method=POST path=/api/oidc/consent remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Request hit" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=debug msg="Authorization Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' is being processed" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=debug msg="Authorization Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' proceeding to lookup consent by challenge id '94bc2819-a635-4960-a993-69721d7eb7f7'" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=debug msg="Authorization Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' loaded consent session with id '36' and challenge id '94bc2819-a635-4960-a993-69721d7eb7f7' for client id '322b825471a545a811e0640435978e80' and subject '4a72128a-120c-493a-aa4e-c616c6dc80cb' and scopes 'openid email profile offline_access'" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=debug msg="Authorization Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Authorization Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' creating session for Authorization Response for subject '4a72128a-120c-493a-aa4e-c616c6dc80cb' with username 'andreas' with claims: &{JTI: Issuer:https://hubbb-authelia-192-168-12-159.traefik.me Subject:4a72128a-120c-493a-aa4e-c616c6dc80cb Audience:[322b825471a545a811e0640435978e80] Nonce: ExpiresAt:0001-01-01 00:00:00 +0000 UTC IssuedAt:2022-06-17 13:47:37.5208268 +0300 EEST m=+34.013166001 RequestedAt:2022-06-17 13:47:21.803452 +0300 EEST AuthTime:2022-06-17 13:47:29 +0300 EEST AccessTokenHash: AuthenticationContextClassReference: AuthenticationMethodsReferences:[pwd] CodeHash: Extra:map[azp:322b825471a545a811e0640435978e80 client_id:322b825471a545a811e0640435978e80 email:andreas.berg@iki.fi email_verified:true name:Andreas Berg preferred_username:andreas]}" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Replied (status=303)" method=GET path=/api/oidc/authorization remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Request hit" method=GET path=/.well-known/openid-configuration remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Replied (status=200)" method=GET path=/.well-known/openid-configuration remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=trace msg="Request hit" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:37+03:00" level=debug msg="Access Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' is being processed" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:38+03:00" level=debug msg="Access Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' has successfully been processed" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:38+03:00" level=trace msg="Access Request with id 'ea005d64-c43c-49ff-b8f0-631e065a747b' on client with id '322b825471a545a811e0640435978e80' produced the following claims: map[access_token:zsidu0W6yIk1KG3KFLPNDMrRlpqiiskJsG-QQUzRluE.WMyQK48dV635diM4RgQd-6LnGvz33vd3yJ3pI_YmX6M expires_in:3600 id_token:eyJhbGciOiJSUzI1NiIsImtpZCI6ImEzN2Q3YyIsInR5cCI6IkpXVCJ9.eyJhbXIiOlsicHdkIl0sImF0X2hhc2giOiIwNmtnOGZ1VUhCQnlacXNvbnpENlRnIiwiYXVkIjpbIjMyMmI4MjU0NzFhNTQ1YTgxMWUwNjQwNDM1OTc4ZTgwIl0sImF1dGhfdGltZSI6MTY1NTQ2Mjg0OSwiYXpwIjoiMzIyYjgyNTQ3MWE1NDVhODExZTA2NDA0MzU5NzhlODAiLCJjbGllbnRfaWQiOiIzMjJiODI1NDcxYTU0NWE4MTFlMDY0MDQzNTk3OGU4MCIsImVtYWlsIjoiYW5kcmVhcy5iZXJnQGlraS5maSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJleHAiOjE2NTU0NjY0NTgsImlhdCI6MTY1NTQ2Mjg1OCwiaXNzIjoiaHR0cHM6Ly9odWJiYi1hdXRoZWxpYS0xOTItMTY4LTEyLTE1OS50cmFlZmlrLm1lIiwianRpIjoiY2VmNmYwNWMtMDExZC00NThjLWJiMGItOTcxNjNjNDNhOTJiIiwibmFtZSI6IkFuZHJlYXMgQmVyZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImFuZHJlYXMiLCJyYXQiOjE2NTU0NjI4NDEsInN1YiI6IjRhNzIxMjhhLTEyMGMtNDkzYS1hYTRlLWM2MTZjNmRjODBjYiJ9.J7U00ihDCyEK5om-8lZVdLvBdCYNLYwx52GhUv_pymJrWqE7r6q1I_o7O4ccUBWkl95pLScpE38XgCD2ZlbVzUPiBJ07ONEiV8tE5izqbRvLGGnYbs3DGWIvso5zDVNHLdVKynRkNjolUgv54aue8yGSp_469VMGSCXMxQq85T0Z0e-ySNkvO18H66XBPKVmrCOiOwXdm6_z0QtVk8k2VYitCpKhV-rc1ukGKD0O-yQTmyj5StGWvLtnbUXVBiqSBvkCNN1gTduK1N-LxGRxUhFvW7WY2_UGXspni0v8HXOiHtlRJRU8IBWL9EmiU1GROJNndoq6kgBZ3Yl1zap8O56wy2Sti2qyXJVUc5VwLjYVLyzOoHOyO_TJjcsz86i_XY0Nk1SirzeM1Un4yyR3IHNyk5Dio3_4joXZr5eHfxMyFYIlA9A7J8HO-FhVsFNmSOHp5Cas_NW_W1rPMU8-R-8WggKx75x77iNvPNOKd5b3lhbfFEcReog6rKuoaeM7W27NP4cr5dIxQP0WK5kEVz_qi5hlcxMf8X5aEb9wnSMmvh0CN9qXUHJpsr3q5kMQPR_CM0h4KGADYFOYMDhY9UOv_KwewQJCS-AGq3Yn4a2nA6QQEHDnDEx5FjX3KBjUfMPUNvMN7w6uj7z7HujpeOshJ20A0CVXU1YEEoRD5Ig refresh_token:jAovNqgLG01IrBfTi_uh0V2YOUXtyKHdPRCuj0Pq-1s.GzGh9XE4nASzLe4N6min-_drhMigla-QW5UhH254xjE scope:openid email profile offline_access token_type:bearer]" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:38+03:00" level=trace msg="Replied (status=200)" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:38+03:00" level=trace msg="Request hit" method=GET path=/jwks.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:38+03:00" level=trace msg="Replied (status=200)" method=GET path=/jwks.json remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:41+03:00" level=trace msg="Request hit" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | time="2022-06-17T13:47:41+03:00" level=debug msg="Access Request with id '4eac93e4-632b-4c30-ad65-e62d3416535d' on client with id '322b825471a545a811e0640435978e80' is being processed" method=POST path=/api/oidc/token remote_ip=172.29.0.1
authelia                  | panic: interface conversion: fosite.Session is *openid.DefaultSession, not *model.OpenIDSession
authelia                  | 
authelia                  | goroutine 71 [running]:
authelia                  | github.com/authelia/authelia/v4/internal/model.NewOAuth2SessionFromRequest({0xc000217830, 0x2b}, {0x55a6ac140ac8, 0xc000390000})
authelia                  | 	github.com/authelia/authelia/v4/internal/model/oidc.go:47 +0x549
authelia                  | github.com/authelia/authelia/v4/internal/oidc.(*OpenIDConnectStore).saveSession(0xc000de9fc8, {0x55a6ac13ae78, 0xc000e2f590}, {0x55a6ab2f43f3, 0xc}, {0xc000217830?, 0x0?}, {0x55a6ac140ac8?, 0xc000390000?})
authelia                  | 	github.com/authelia/authelia/v4/internal/oidc/store.go:312 +0x7a
authelia                  | github.com/authelia/authelia/v4/internal/oidc.(*OpenIDConnectStore).CreateAccessTokenSession(0xc0002e2230?, {0x55a6ac13ae78?, 0xc000e2f590?}, {0xc000217830?, 0xc0002e2200?}, {0x55a6ac140ac8?, 0xc000390000?})
authelia                  | 	github.com/authelia/authelia/v4/internal/oidc/store.go:174 +0x50
authelia                  | github.com/ory/fosite/handler/oauth2.(*RefreshTokenGrantHandler).PopulateTokenEndpointResponse(0xc0002a69a0, {0x55a6ac13ae78, 0xc0002d11d0}, {0x55a6ac140cc0, 0xc0002e2200}, {0x55a6ac13e898, 0xc0002d1140})
authelia                  | 	github.com/ory/fosite@v0.42.2/handler/oauth2/flow_refresh.go:166 +0x81e
authelia                  | github.com/ory/fosite.(*Fosite).NewAccessResponse(0xc0000a9e00, {0x55a6ac13b0a8, 0xc000672900}, {0x55a6ac140cc0?, 0xc0002e2200})
authelia                  | 	github.com/ory/fosite@v0.42.2/access_response_writer.go:42 +0x450
authelia                  | github.com/authelia/authelia/v4/internal/handlers.OpenIDConnectTokenPOST(0xc000672900, {0x55a6ac137888, 0xc000e2f2c0}, 0xc000405f20?)
authelia                  | 	github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:47 +0x47c
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.NewHTTPToAutheliaHandlerAdaptor.func1(0xc000672900)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113 +0x4e8
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.(*BridgeBuilder).Build.func1.1(0xc0002de898?)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/bridge.go:54 +0xe9
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.SecurityHeadersNoStore.func1(0xc0002de580)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/headers.go:35 +0xaa
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.SecurityHeadersCSPNone.func1(0xc0002de580)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/headers.go:25 +0x6d
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.SecurityHeaders.func1(0xc0002de580)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/headers.go:16 +0x149
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.CORSPolicy.Middleware.func1(0xc000268790?)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/cors.go:216 +0x7a
authelia                  | github.com/fasthttp/router.(*Router).Handler(0xc0002a6af0, 0xc0002de580)
authelia                  | 	github.com/fasthttp/router@v1.4.10/router.go:414 +0x46a
authelia                  | github.com/authelia/authelia/v4/internal/middlewares.LogRequest.func1(0xc0002de580)
authelia                  | 	github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 +0xb1
authelia                  | github.com/valyala/fasthttp.(*Server).serveConn(0xc000366d80, {0x55a6ac13e670?, 0xc0000103a0})
authelia                  | 	github.com/valyala/fasthttp@v1.37.0/server.go:2338 +0x1268
authelia                  | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000c48c0, 0xc000316500)
authelia                  | 	github.com/valyala/fasthttp@v1.37.0/workerpool.go:224 +0xa9
authelia                  | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
authelia                  | 	github.com/valyala/fasthttp@v1.37.0/workerpool.go:196 +0x38
authelia                  | created by github.com/valyala/fasthttp.(*workerPool).getCh
authelia                  | 	github.com/valyala/fasthttp@v1.37.0/workerpool.go:195 +0x1b0
```

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

I'm away for the weekend, available for further info/testing/debugging next week.

**Comment by james-d-elliott** [comment]
I'll make a fix to the interface conversion as I made a critical mistake there. Though I'm utterly surprised it is possible to have that type.

**Comment by andreas-berg** [comment]
Tested with current master including the PR #3538, I can confirm that there is no Panic anymore 🤩 but there is some underlying conversion problem still: "can't convert type '*openid.DefaultSession' to an *OAuth2Session"

OpenIDC and Oauth2 are to my understanding basically identical except that OIDC provides the interface descriptions in the ".well-known/openid-configuration". I'm using OIDC in this case and try to follow [this specification](https://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken) for refreshing tokens. 
Is this suppose to work?

**Comment by james-d-elliott** [comment]
The `OAuth2Session` is basically a `openid.DefaultSession` with extra values. The later comes from a library, and the former is our implementation of it. We named it thus because it's used for both OpenID and OAuth2. 

As to why this is occuring.. I'm not entirely sure. We never newup  a openid.Default session except in the context of a OAuth2Session. So it's very strange this value is being stored. I did add some additional trace logging in my commit: https://github.com/authelia/authelia/commit/d9c7cd65643f65722fa00736aeb662a86046d689#diff-9529d191106dc5c1dfcd80820161ab6cae0b303ab49643d5ea62116174beb10eR47

This may be helpful in diagnosing it.

**Comment by nick-oconnor** [comment]
FWIW I'm running into this issue as well. Both roundcube and oauth2-proxy trigger the conversion issue.

**Comment by nick-oconnor** [comment]
I've enabled tracing and I've been able to see both object types being created. There's a lot of log noise so let me know if you need a larger excerpt, but here are two traces (all logs with the trace id):
```
time="2022-06-27T04:16:51Z" level=debug msg="Access Request with id 'd523ac10-ccef-4978-8a13-f2a3b2ae3fc2' on client with id 'roundcube' is being processed" method=POST path=/api/oidc/token remote_ip=10.66.20.1
time="2022-06-27T04:16:51Z" level=trace msg="Access Request with id 'd523ac10-ccef-4978-8a13-f2a3b2ae3fc2' on client with id 'roundcube' response is being generated for session with type '*openid.DefaultSession'" method=POST path=/api/oidc/token remote_ip=10.66.20.1
time="2022-06-27T04:16:51Z" level=error msg="Access Response for Request with id 'd523ac10-ccef-4978-8a13-f2a3b2ae3fc2' failed to be created with error: The authorization server encountered an unexpected condition that prevented it from fulfilling the request. can't convert type '*openid.DefaultSession' to an *OAuth2Session" method=POST path=/api/oidc/token remote_ip=10.66.20.1 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:52...
```
```
time="2022-06-27T04:17:11Z" level=debug msg="Access Request with id 'de0860c8-5e79-4a4b-98bf-b3f85fc262a5' on client with id 'roundcube' is being processed" method=POST path=/api/oidc/token remote_ip=10.66.20.1
time="2022-06-27T04:17:11Z" level=trace msg="Access Request with id 'de0860c8-5e79-4a4b-98bf-b3f85fc262a5' on client with id 'roundcube' response is being generated for session with type '*model.OpenIDSession'" method=POST path=/api/oidc/token remote_ip=10.66.20.1
time="2022-06-27T04:17:11Z" level=debug msg="Access Request with id 'de0860c8-5e79-4a4b-98bf-b3f85fc262a5' on client with id 'roundcube' has successfully been processed" method=POST path=/api/oidc/token remote_ip=10.66.20.1
time="2022-06-27T04:17:11Z" level=trace msg="Access Request with id 'de0860c8-5e79-4a4b-98bf-b3f85fc262a5' on client with id 'roundcube' produced the following claims: map[access_token:<redacted> expires_in:600 id_token:<redacted> refresh_token:<redacted> scope:openid email profile groups offline_access token_type:bearer]" method=POST path=/api/oidc/token remote_ip=10.66.20.1
```

**Comment by james-d-elliott** [comment]
Yeah that should be enough, I will just have to work on replication and figure out what I've done wrong.

**Comment by nick-oconnor** [comment]
@james-d-elliott this looks suspicious https://github.com/ory/fosite/blob/d71c67ff5431c0ce7a47cda6b871d4fd68e7247e/handler/oauth2/flow_refresh.go#L98

**Comment by james-d-elliott** [comment]
Yeah I've been relatively sure for a week or so that this would be the case, and we just have to create the wrapped session ourselves which will be fine *I think*.

**Comment by james-d-elliott** [comment]
Looking at how Hydra uses this, it's almost identical. I am wondering if we just need to override the Clone() method like they do.

**Comment by nick-oconnor** [comment]
@james-d-elliott your fix makes sense to me. I'll test it today.

**Comment by nick-oconnor** [comment]
@james-d-elliott no errors so far refreshing tokens :tada:. I tested with a 10m token expiration with both roundcube (refresh after expiration) and oauth2-proxy (refresh before expiration). It maybe a good idea to add some testing around the OIDC flows if possible.

**Comment by james-d-elliott** [comment]
We have some integration testing, but yes it'd be good to implement some more comprehensive testing. It's so weird to me that this fixed it: https://github.com/authelia/authelia/pull/3603/files

**Comment by james-d-elliott** [comment]
> To your point, it looks like Hydra addressed this [in the same way](https://github.com/ory/hydra/blob/1faa00b6a0abab141be376f063583ade83681318/oauth2/session.go#L120).

Yeah this is what I thought may be the case when I saw it. Just am not entirely sure how copying from one fosite.Session to another fosite.Session solves it, I suspect it's because it's an interface and the implementation is what matters here combined with the fact that it's the embedded function call like you said, which makes sense, the embedded function only has access to its own fields.

**Comment by andreas-berg** [comment]
Nice fix guys! 
Tested with immediate refresh and I can confirm this work, now the whole refresh-token flow from nextauth works for me.
Thanks!
