### ISSUE TITLE
LDAP and Error: Size Limit Exceeded with users_filter

### ISSUE THREAD

**Issue by bu3tt1** [authelia/authelia#379]
First of all thanks for the Authelia, it's a good product!

I am configuring Authelia with OpenLDAP, and in this regard I have lost several hours in finding the cause of an error.

During ldap authentication the following error occurred: Error: Size Limit Exceeded

**The logs:**
```
authelia        | debug: date='Wed Jul 03 2019 06:40:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='...
authelia        | info: date='Wed Jul 03 2019 06:40:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='...
authelia        | info: date='Wed Jul 03 2019 06:40:00 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='...
authelia        | debug: LDAP: Bind user 'uid=username,dc=domain,dc=com'
openldap        | 5d1c4dc1 conn=1300 fd=12 ACCEPT from IP=175.0.0.4:6666 (IP=0.0.0.0:389)
openldap        | 5d1c4dc1 conn=1300 op=0 BIND dn="uid=username,dc=domain,dc=com" method=128
openldap        | 5d1c4dc1 conn=1300 op=0 BIND dn="uid=username,dc=domain,dc=com" mech=SIMPLE ssf=0
openldap        | 5d1c4dc1 conn=1300 op=0 RESULT tag=97 err=0 text=
authelia        | debug: Computed users filter is (memberOf=cn=authelia_users,cn=groups,dc=domain,dc=com)
authelia        | debug: LDAP: searching for user dn of fdsf
openldap        | 5d1c4dc1 conn=1300 op=1 SRCH base="cn=users,dc=domain,dc=com" scope=2 deref=0 filter="(memberOf=cn=authelia_users,cn=groups,dc=domain,dc=com)"
openldap        | 5d1c4dc1 conn=1300 op=1 SRCH attr=dn
openldap        | 5d1c4dc1 conn=1300 op=1 SEARCH RESULT tag=101 err=4 nentries=1 text=
authelia        | debug: LDAP: Unbind user 'uid=username,dc=domain,dc=com'
openldap        | 5d1c4dc1 conn=1300 op=2 UNBIND
openldap        | 5d1c4dc1 conn=1300 fd=12 closed
authelia        | error: date='Wed Jul 03 2019 06:40:01 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' ... message='Reply with error 200: Size Limit Exceeded'
authelia        | debug: date='Wed Jul 03 2019 06:40:01 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' ... message='Error: Size Limit Exceeded
authelia        |     at that.withSession.catch (/usr/src/server/src/lib/authentication/backends/ldap/LdapUsersDatabase.js:33:45)
authelia        |     at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
authelia        |     at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:512:31)
authelia        |     at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:569:18)
authelia        |     at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:614:10)
authelia        |     at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:690:18)
authelia        |     at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:138:12)
authelia        |     at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:131:9)
authelia        |     at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:147:5)
authelia        |     at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:17:14)
authelia        |     at runCallback (timers.js:785:20)
authelia        |     at tryOnImmediate (timers.js:747:5)
authelia        |     at processImmediate [as _immediateCallback] (timers.js:718:5)'
```

**Configuration of the query:**
users_filter: (memberOf=cn=authelia_users,cn=groups,dc=domain,dc=com)

I started looking for the problem in the LDAP configuration, looking for the limit that was configured to 500. I tested the Query and found that it was below the limit of 500 records.

After several hours I came to the conclusion that it was not a problem with the "Size Limit Exceeded", but with probably a client limit and the query that returns more records. Authelia probably only expects one record, the user, instead my query returned more records.

**Corrected query:**
users_filter: (&(memberOf=cn=authelia_users,cn=groups,dc=domain,dc=com)(uid={0}))

My problem is solved, but I open the issue to document my problem and to ask if it is possible to change the Authelia debugging message and return something like: expect only one record, more are returned

**Comment by clems4ever** [comment]
Hello @bu3tt1 , thank you for the report. Indeed Authelia expect to get only one user and I agree that the message is not clear enough. I will add a test case for that and improve the log message in the next major. Thanks.

**Comment by bu3tt1** [comment]
Thank you very much

**Comment by clems4ever** [comment]
Hello @bu3tt1 , this issue has been reported in v3 but is unlikely to appear in v4. If you've not yet upgraded yet to v4, I invite you to do so and re-open this issue if it's not solved.
