### ISSUE TITLE
subject: 'group:admin' not working with ldap

### ISSUE THREAD

**Issue by Paramosh** [authelia/authelia#397]
Hi, authelia does not see user group
for example log:
```
debug: Computed users filter is sAMAccountName=john
debug: LDAP: searching for user dn of john
debug: LDAP: retrieved user dn is CN=John Wick,OU=user,DC=example,DC=com
debug: Computed groups filter is (&(member=CN=John Wick,OU=user,DC=example,DC=com)(objectclass=group))
debug: LDAP: emails of user 'john' are john@example.com
debug: LDAP: groups of user john are [admin,killers]
```
authelia config.yml rule: 
```
- domain: '*.example.com'
      subject: 'group:admin'
      policy: one_factor
```
```
ldap:
    url: ldap://ldap.example.com
    base_dn: dc=example, dc=com
    users_filter: sAMAccountName={0}
    groups_filter: (&(member={dn})(objectclass=group))
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=admin,ou=user,dc=example,dc=com
    password: password
```

and for user john after entering login and pass, 2 factor asks
default policy = deny

**Comment by clems4ever** [comment]
What URL do you visit and what behavior do you expect?

**Comment by Paramosh** [comment]
address for example:
site1.example.com
I was hoping to set up group membership access in the ldap,
If the user is a member of the 'admin' group in the domain then start up one factor
else policy deny and access denied :)

Maybe I didn’t understand correctly how group and user filters work. :(

**Comment by nightah** [comment]
@Paramosh can you paste your full config.yml, feel free to redact passwords.

**Comment by Paramosh** [comment]
@nightah, i take minimal config
```
###############################################################
#                Authelia minimal configuration               #
###############################################################
port: 9091

logs_level: debug

authentication_backend:

  ldap:
    url: ldap://ldap.example.com
    base_dn: dc=example, dc=com
    users_filter: sAMAccountName={0}
    groups_filter: (&(member={dn})(objectclass=group))
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=admin,ou=user,dc=example,dc=com
    password: <password>

session:
  secret: unsecure_session_secret
  domain: example.com

# Configuration of the storage backend used to store data and secrets. i.e. totp data
storage:
  local:
    path: /etc/authelia/storage

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
#totp:
##  issuer: example.com

# Access Control
#
# Access control is a set of rules you can use to restrict user access to certain 
# resources.
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  default_policy: deny

  rules:
      # Rules applied to everyone
      - domain: site1.example.com
        subject: 'group:admin'
        policy: one_factor
      - domain: site2.example.com
        subject: 'group: poweruser'
        policy: two_factor

# Configuration of the authentication regulation mechanism.
regulation: 
  # Set it to 0 to disable max_retries.
  max_retries: 3

  # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window. 
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Default redirection URL
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
#default_redirection_url: https://authelia.example.domain

notifier:
  # For testing purpose, notifications can be sent in a file
  filesystem:
    filename: /tmp/authelia/notification.txt
```

**Comment by nightah** [comment]
With the above config you're saying that when you visit `site1.example.com` with a user that's part of the `admin` group and it does not work?
Can you provide the authelia logs too for this?

**Comment by Paramosh** [comment]
```

info: date='Thu Sep 26 2019 04:57:46 GMT+0000 (UTC)' message='Starting Authelia...'


info: date='Thu Sep 26 2019 04:57:46 GMT+0000 (UTC)' message='Listening on port 9091...'


debug: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Headers = {"x-real-ip":"192.168.240.1","x-forwarded-proto":"https","x-forwarded-host":"login.example.com:8080","x-forwarded-for":"192.168.240.1","host":"192.168.240.1:9091","connection":"close","content-length":"69","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"application/json","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://login.example.com:8080/","content-type":"application/json","x-target-url":"https://site1.example.com:8080/","origin":"https://login.example.com:8080","dnt":"1"}'


info: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Starting authentication of user "john"'


debug: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Authentication session 2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw was undefined. Resetting... If it's unexpected, make sure you are visiting the expected domain.'


info: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='No regulation applied.'


debug: LDAP: Bind user 'cn=admin,ou=user,dc=example,dc=com'


debug: Computed users filter is sAMAccountName=john


debug: LDAP: searching for user dn of john


debug: LDAP: retrieved user dn is CN=John Wick,OU=user,DC=example,DC=com


debug: LDAP: Bind user 'cn=admin,ou=user,dc=example,dc=com'


debug: LDAP: Unbind user 'cn=admin,ou=user,dc=example,dc=com'


debug: Computed groups filter is (&(member=CN=John Wick,OU=user,DC=example,DC=com)(objectclass=group))


debug: LDAP: emails of user 'john' are john@example.com


debug: LDAP: groups of user john are [admin,ProjectUsers,RadminAdmins]


debug: LDAP: Unbind user 'cn=admin,ou=user,dc=example,dc=com'


info: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='LDAP binding successful. Retrieved information about user are {"groups":[admin,ProjectUsers,RadminAdmins],"emails":["john@example.com"]}'


debug: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Mark successful authentication to regulator.'


debug: date='Thu Sep 26 2019 04:58:09 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='a7c6bd05-fef3-4279-972a-1610d5bb402e' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Header x-target-url is set to https://site1.example.com:8080/'


debug: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='f4aa5c31-b5b3-4766-b1ea-b1f160fc22f4' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Headers = {"x-real-ip":"192.168.240.1","x-original-url":"https://site1.example.com:8080/","x-forwarded-proto":"https","x-forwarded-host":"site1.example.com:8080","x-forwarded-uri":"/","x-forwarded-for":"192.168.240.1","host":"192.168.240.1:9091","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","dnt":"1","referer":"https://login.example.com:8080/","cookie":"authelia_session=s%3A2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw.eKP5mvHUaDe4jbX8bPbzO9Sgxatl1eL4uD85%2B4FP01M","upgrade-insecure-requests":"1"}'


debug: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='f4aa5c31-b5b3-4766-b1ea-b1f160fc22f4' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Header x-original-url is set to https://site1.example.com:8080/'


debug: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='f4aa5c31-b5b3-4766-b1ea-b1f160fc22f4' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='domain=site1.example.com, path=/, user=john, groups=admin,ProjectUsers,RadminAdmins, ip=192.168.240.1'


debug: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='f4aa5c31-b5b3-4766-b1ea-b1f160fc22f4' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Header x-original-url is set to https://site1.example.com:8080/'


error: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='f4aa5c31-b5b3-4766-b1ea-b1f160fc22f4' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Reply with error 401: The header content contains invalid characters'


debug: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='f4aa5c31-b5b3-4766-b1ea-b1f160fc22f4' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='TypeError: The header content contains invalid characters


    at validateHeader (_http_outgoing.js:492:11)


    at ServerResponse.setHeader (_http_outgoing.js:496:3)


    at Object.default_1 [as default] (/usr/src/server/src/lib/routes/verify/SetUserAndGroupsHeaders.js:8:13)


    at Object.<anonymous> (/usr/src/server/src/lib/routes/verify/GetSessionCookie.js:31:42)


    at Generator.next (<anonymous>)


    at /usr/src/server/src/lib/routes/verify/GetSessionCookie.js:7:71


    at new Promise (<anonymous>)


    at __awaiter (/usr/src/server/src/lib/routes/verify/GetSessionCookie.js:3:12)


    at Object.default_1 [as default] (/usr/src/server/src/lib/routes/verify/GetSessionCookie.js:17:12)


    at /usr/src/server/src/lib/routes/verify/Get.js:25:45


    at Generator.next (<anonymous>)


    at /usr/src/server/src/lib/routes/verify/Get.js:7:71


    at new Promise (<anonymous>)


    at __awaiter (/usr/src/server/src/lib/routes/verify/Get.js:3:12)


    at verifyWithSelectedMethod (/usr/src/server/src/lib/routes/verify/Get.js:20:12)


    at /usr/src/server/src/lib/routes/verify/Get.js:38:19'


debug: date='Thu Sep 26 2019 04:58:10 GMT+0000 (UTC)' method='GET', path='/api/state' requestId='ec5c1271-8239-4943-a033-be9b1bb94c2f' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Headers = {"x-real-ip":"192.168.240.1","x-forwarded-proto":"https","x-forwarded-host":"login.example.com:8080","x-forwarded-for":"192.168.240.1","host":"192.168.240.1:9091","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://login.example.com:8080/","dnt":"1","cookie":"authelia_session=s%3A2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw.eKP5mvHUaDe4jbX8bPbzO9Sgxatl1eL4uD85%2B4FP01M","if-none-match":"W/\"1a-WDeCm39gGM0/ubzz9lBRjjvLOdo\""}'


debug: date='Thu Sep 26 2019 04:58:11 GMT+0000 (UTC)' method='GET', path='/api/secondfactor/preferences' requestId='76af1fb4-d375-4b0c-876a-16e7ffd5304a' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Headers = {"x-real-ip":"192.168.240.1","x-forwarded-proto":"https","x-forwarded-host":"login.example.com:8080","x-forwarded-for":"192.168.240.1","host":"192.168.240.1:9091","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://login.example.com:8080/","dnt":"1","cookie":"authelia_session=s%3A2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw.eKP5mvHUaDe4jbX8bPbzO9Sgxatl1eL4uD85%2B4FP01M"}'


debug: date='Thu Sep 26 2019 04:58:11 GMT+0000 (UTC)' method='GET', path='/api/secondfactor/available' requestId='fa3ebbdb-2e8b-404f-a98d-3ffc3e3da0ed' sessionId='2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw' ip='192.168.240.1' message='Headers = {"x-real-ip":"192.168.240.1","x-forwarded-proto":"https","x-forwarded-host":"login.example.com:8080","x-forwarded-for":"192.168.240.1","host":"192.168.240.1:9091","connection":"close","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"*/*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","referer":"https://login.example.com:8080/","dnt":"1","cookie":"authelia_session=s%3A2wZcdLTu2XQCCXnZCLJMTXA89p7VyaCw.eKP5mvHUaDe4jbX8bPbzO9Sgxatl1eL4uD85%2B4FP01M"}'
```

**Comment by Paramosh** [comment]
Maybe headers in nginx config lost?
config take in folder example in project

```
#
# You can find a documented example of configuration in ./docs/proxies/nginx.md.
#


worker_processes  1;

events {
    worker_connections  1024;
}

http {
    
    server {
        listen 8080 ssl;
        server_name     login.example.com;

        resolver 127.0.0.11 ipv6=off;
        set $frontend_endpoint http://192.168.240.1:9091;
        set $backend_endpoint http://192.168.240.1:9091;

        ssl_certificate     /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";

        # Serve the backend API for the portal.
        location /api {
            proxy_set_header  X-Real-IP $remote_addr;

            # Required by Authelia because "trust proxy" option is used.
            # See https://expressjs.com/en/guide/behind-proxies.html
            proxy_set_header  X-Forwarded-Proto $scheme;

            # Required by Authelia to build correct links for identity validation.
            proxy_set_header  X-Forwarded-Host $http_host;

            # Needed for network ACLs to work. It appends the IP of the client to the list of IPs
            # and allows Authelia to use it to match the network-based ACLs.
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_intercept_errors on;

            proxy_pass        $backend_endpoint;
        }

        # Serves the portal application.
        location / {
            # Allow websockets for webpack to auto-reload.
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_pass        $frontend_endpoint;
        }
    }
    

    # Example configuration of domains protected by Authelia.
    server {
        listen 8080 ssl; 
        server_name     site1.example.com
                        site2.example.com
                        
        resolver 127.0.0.11 ipv6=off;
        set $upstream_verify http://192.168.240.1:9091/api/verify;
        set $upstream_endpoint http://nginx-backend;
        set $upstream_headers http://192.168.240.1:8000/headers;

        ssl_certificate     /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";

        # Reverse proxy to the backend. It is protected by Authelia by forwarding authorization checks
        # to the virtual endpoint introduced by nginx and declared in the next block.
        location / {
            auth_request /auth_verify;
            
            auth_request_set $user      $upstream_http_remote_user;
            proxy_set_header            X-Forwarded-User $user;
            
            auth_request_set            $groups $upstream_http_remote_groups;
            proxy_set_header            Remote-Groups $groups;

            # Route the request to the correct virtual host in the backend.
            proxy_set_header            Host $http_host;

            # Authelia relies on Proxy-Authorization header to authenticate in basic auth.
            # but for the sake of simplicity (because Authorization in supported in most
            # clients) we take Authorization from the frontend and rewrite it to
            # Proxy-Authorization before sending it to Authelia.
            proxy_set_header            Proxy-Authorization $http_authorization;

            # mitigate HTTPoxy Vulnerability
            # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
            proxy_set_header            Proxy "";

            # Set the `target_url` variable based on the request. It will be used to build the portal
            # URL with the correct redirection parameter.
            set                         $target_url $scheme://$http_host$request_uri;
            error_page 401 =302         https://login.example.com:8080/#/?rd=$target_url;

            proxy_pass                  $upstream_endpoint;
        }

        # Virtual endpoint forwarding requests to Authelia server.
        location /auth_verify {
            internal;
            proxy_set_header            X-Real-IP $remote_addr;

            # Provide either X-Original-URL and X-Forwarded-Proto or
            # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
            # Those headers will be used by Authelia to deduce the target url of the user.
            #
            # X-Forwarded-Proto is mandatory since Authelia uses the "trust proxy" option.
            # See https://expressjs.com/en/guide/behind-proxies.html
            proxy_set_header            X-Original-URL $scheme://$http_host$request_uri;

            proxy_set_header            X-Forwarded-Proto $scheme;
            proxy_set_header            X-Forwarded-Host $http_host;
            proxy_set_header            X-Forwarded-Uri $request_uri;
            
            proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;

            # Authelia can receive Proxy-Authorization to authenticate however most of the clients
            # support Authorization instead. Therefore we rewrite Authorization into Proxy-Authorization.
            proxy_set_header            Proxy-Authorization $http_authorization;

            proxy_pass_request_body     off;
            proxy_set_header            Content-Length "";

            proxy_pass                  $upstream_verify;
        }

        # Used by suites to test the forwarded users and groups headers produced by Authelia.
        location /headers {
            auth_request /auth_verify;

            auth_request_set            $user $upstream_http_remote_user;
            proxy_set_header            Custom-Forwarded-User $user;
            
            auth_request_set            $groups $upstream_http_remote_groups;
            proxy_set_header            Custom-Forwarded-Groups $groups;

            set                         $target_url $scheme://$http_host$request_uri;
            error_page 401 =302         https://login.example.com:8080/#/?rd=$target_url;

            proxy_pass                  $upstream_headers;
        }
    }

    # Fake Web Mail used to receive emails sent by Authelia.
    server {
        listen 8080 ssl;
        server_name     mail.example.com;

        resolver 127.0.0.11 ipv6=off;
        set $upstream_endpoint http://smtp:1080;

        ssl_certificate     /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";

        location / {
            proxy_set_header  Host $http_host;
            proxy_pass        $upstream_endpoint;
        }
    }

    # Fake API emulating Duo behavior
    server {
        listen 443 ssl;
        server_name     duo.example.com;

        resolver 127.0.0.11 ipv6=off;
        set $upstream_endpoint http://duo-api:3000;

        ssl_certificate     /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";

        location / {
            proxy_set_header  Host $http_host;
            proxy_pass        $upstream_endpoint;
        }
    }
}

```

**Comment by nightah** [comment]
> @nightah, i take minimal config
> 
> ```
> ###############################################################
> #                Authelia minimal configuration               #
> ###############################################################
> port: 9091
> 
> logs_level: debug
> 
> authentication_backend:
> 
>   ldap:
>     url: ldap://ldap.example.com
>     base_dn: dc=example, dc=com
>     users_filter: sAMAccountName={0}
>     groups_filter: (&(member={dn})(objectclass=group))
>     group_name_attribute: cn
>     mail_attribute: mail
>     user: cn=admin,ou=user,dc=example,dc=com
>     password: <password>
> 
> session:
>   secret: unsecure_session_secret
>   domain: example.com
> 
> # Configuration of the storage backend used to store data and secrets. i.e. totp data
> storage:
>   local:
>     path: /etc/authelia/storage
> 
> # TOTP Issuer Name
> #
> # This will be the issuer name displayed in Google Authenticator
> # See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
> #totp:
> ##  issuer: example.com
> 
> # Access Control
> #
> # Access control is a set of rules you can use to restrict user access to certain 
> # resources.
> access_control:
>   # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
>   default_policy: deny
> 
>   rules:
>       # Rules applied to everyone
>       - domain: site1.example.com
>         subject: 'group:admin'
>         policy: one_factor
>       - domain: site2.example.com
>         subject: 'group: poweruser'
>         policy: two_factor
> 
> # Configuration of the authentication regulation mechanism.
> regulation: 
>   # Set it to 0 to disable max_retries.
>   max_retries: 3
> 
>   # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window. 
>   find_time: 120
> 
>   # The length of time before a banned user can login again.
>   ban_time: 300
> 
> # Default redirection URL
> #
> # Note: this parameter is optional. If not provided, user won't
> # be redirected upon successful authentication.
> #default_redirection_url: https://authelia.example.domain
> 
> notifier:
>   # For testing purpose, notifications can be sent in a file
>   filesystem:
>     filename: /tmp/authelia/notification.txt
> ```

Can you try uncomment the following lines in your authelia config:
```
#totp:
##  issuer: example.com
```

**Comment by Paramosh** [comment]
@nightah 
without changes

```
method='GET', path='/api/verify'
message='Reply with error 401: The header content contains invalid characters
message='TypeError: The header content contains invalid characters
```
 
I had the idea that the group may be transferred to the header in the wrong encoding.

as an example, a group in сyrillic = "группа" :(

**Comment by Paramosh** [comment]
really, if the groups have cyrillic, the config does not work, if only the latin works fine
Created users_database.yml with user and testing then

it does not work:
```
# List of users
users:
  john:
    password: "{CRYPT}$6$rounds=500000$dYzvyCj26kD1SJM$4i.Yd0mY6Rji.EHFvbNKK8a2KrTZYA7yCPYfA2Re3mZXq.AsHwzW5jYM.zsOPyRNKuMxOZjB8RivyIrJylv2H/"
    email: john.doe@authelia.com
    groups:
      - admins
      - killers
      - группа
```

it work:
```
# List of users
users:
  john:
    password: "{CRYPT}$6$rounds=500000$dYzvyCj26kD1SJM$4i.Yd0mY6Rji.EHFvbNKK8a2KrTZYA7yCPYfA2Re3mZXq.AsHwzW5jYM.zsOPyRNKuMxOZjB8RivyIrJylv2H/"
    email: john.doe@authelia.com
    groups:
      - admins
      - killers
```

**Comment by clems4ever** [comment]
Got it. Definitely a bug then. I'll try to have a look.

**Comment by Paramosh** [comment]
maybe someone as a temporary solution can tell how you can remove the cyrillic from the proxy_set_header            Remote-Groups $groups;
variable on the nginx side?))))

**Comment by clems4ever** [comment]
Hello @Paramosh , can you retry with v4?

**Comment by Paramosh** [comment]
Of course, I’ll update the version and write here

**Comment by Paramosh** [comment]
Yes, he apparently processes the group correctly
for

`# List of users
users:
  john:
    password: "{CRYPT}$6$rounds=500000$dYzvyCj26kD1SJM$4i.Yd0mY6Rji.EHFvbNKK8a2KrTZYA7yCPYfA2Re3mZXq.AsHwzW5jYM.zsOPyRNKuMxOZjB8RivyIrJylv2H/"
    email: john.doe@authelia.com
    groups:
      - admins
      - killers
      - группа`
no problem.

But with a request for LDAP
`Unable to retrieve groups of user john. Cause: LDAP Result Code 34 \"Invalid DN Syntax\", problem 2006 (BAD_NAME)`

in v3 request return group

**Comment by james-d-elliott** [comment]
This is caused by additional_groups_dn being blank or commented. I found the same issue. In v3 if you comment it out it just searches the base_dn.

`time="2019-12-19T08:58:13+11:00" level=error msg="Error while retrieving details from user jsmith: Unable to retrieve groups of user jsmith. Cause: LDAP Result Code 34 \"Invalid DN Syntax\": 0000208F: NameErr: DSID-0310022E, problem 2006 (BAD_NAME), data 8350, best match of:\n\t',DC=contoso,DC=com'\n\x00" method=POST path=/api/firstfactor remote_ip=10.44.0.5 stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_firstfactor.go:92          FirstFactorPost\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"`

`  authentication_backend:
    ldap:
      url: ldap://dc1:3268
      skip_verify: false
      base_dn: DC=contoso,DC=com
      additional_users_dn: OU=Accounts
      # additional_groups_dn: OU=Groups
      users_filter: (sAMAccountName={0})
      groups_filter: (&(member={dn})(objectClass=group))
      group_name_attribute: cn
      mail_attribute: mail
      user: CN=Authelia,OU=Accounts,DC=contoso,DC=com
      password: password`

**Comment by Paramosh** [comment]
@james-d-elliott @clems4ever 
I updated from the master branch and everything works fine

**Comment by nightah** [comment]
@Paramosh do you mean with LDAP also?

**Comment by nightah** [comment]
@Paramosh I'm going to close this issue off, if you experience issues please lodge a new issue.

**Comment by Paramosh** [comment]
Yeah! with LDAP
