### ISSUE TITLE
Crash when sending Emails

### ISSUE THREAD

**Issue by speatzle** [authelia/authelia#5680]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.6.4

### Description

Sometimes when sending emails for password resets the error `panic: runtime error: invalid memory address or nil pointer dereference` occurs and Authelia crashes. The Email gets sent successfully anyway.

Curiously systemd did not start authelia again automatically which suggests that there is also an issue with the systemd unit file.

### Reproduction

Not sure, send a lot of emails?

### Configuration (Authelia)

```yaml
Just normal email StartTLS connection to a mailcow (postfix) server.
```

### Logs (Authelia)

```shell
Jul 14 07:24:07 authelia authelia[16067]: time="2023-07-14T07:24:07Z" level=debug msg="Notifier SMTP client successfully sent email"
Jul 14 07:24:07 authelia authelia[16067]: time="2023-07-14T07:24:07Z" level=debug msg="Notifier SMTP client successfully sent email"
Jul 14 07:24:07 authelia authelia[16067]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 14 07:24:07 authelia authelia[16067]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x55db61e6e6d8]
Jul 14 07:24:07 authelia authelia[16067]: goroutine 390932 [running]:
Jul 14 07:24:07 authelia authelia[16067]: net/smtp.(*Client).hello(0xc000380000?)
Jul 14 07:24:07 authelia authelia[16067]:         net/smtp/smtp.go:83 +0x18
Jul 14 07:24:07 authelia authelia[16067]: net/smtp.(*Client).Quit(0x0)
Jul 14 07:24:07 authelia authelia[16067]:         net/smtp/smtp.go:416 +0x25
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/notification.(*SMTPNotifier).cleanup(0xc000e9aec0)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:327 +0x29
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/notification.(*SMTPNotifier).Send(0xc000e9aec0, {{0xc0010e08c0?, 0xc0000a91e0?}, {0xc000f3c740?, 0x55db61ff2c74?}}, {0x55db620aadeb, 0x13}, {0xc000346000, 0x2e5, 0x500}, ...)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:75 +0x352
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/middlewares.IdentityVerificationStart.func1(0xc000ed4c00)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:105 +0xb4f
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/middlewares.(*BridgeBuilder).Build.func1.1(0xc000aae330?)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/middlewares/bridge.go:54 +0xe9
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/middlewares.SecurityHeadersCSPNone.func1(0xc000aae000)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/middlewares/headers.go:25 +0x6d
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/middlewares.SecurityHeadersNoStore.func1(0xc000aae000)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/middlewares/headers.go:35 +0xaa
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/middlewares.SecurityHeaders.func1(0xc000aae000)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/middlewares/headers.go:16 +0x149
Jul 14 07:24:07 authelia authelia[16067]: github.com/fasthttp/router.(*Router).Handler(0xc000218000, 0xc000aae000)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/fasthttp/router@v1.4.14/router.go:414 +0x46a
Jul 14 07:24:07 authelia authelia[16067]: github.com/authelia/authelia/v4/internal/middlewares.LogRequest.func1(0xc000aae000)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 +0xb1
Jul 14 07:24:07 authelia authelia[16067]: github.com/valyala/fasthttp.(*Server).serveConn(0xc00041a240, {0x55db631acf10?, 0xc0001142d8})
Jul 14 07:24:07 authelia authelia[16067]:         github.com/valyala/fasthttp@v1.43.0/server.go:2338 +0x1268
Jul 14 07:24:07 authelia authelia[16067]: github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000ecdb80, 0xc00027a180)
Jul 14 07:24:07 authelia authelia[16067]:         github.com/valyala/fasthttp@v1.43.0/workerpool.go:224 +0xa9
Jul 14 07:24:07 authelia authelia[16067]: github.com/valyala/fasthttp.(*workerPool).getCh.func1()
Jul 14 07:24:07 authelia authelia[16067]:         github.com/valyala/fasthttp@v1.43.0/workerpool.go:196 +0x38
Jul 14 07:24:07 authelia authelia[16067]: created by github.com/valyala/fasthttp.(*workerPool).getCh
Jul 14 07:24:07 authelia authelia[16067]:         github.com/valyala/fasthttp@v1.43.0/workerpool.go:195 +0x1b0
Jul 14 07:24:07 authelia systemd[1]: authelia.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 14 07:24:07 authelia systemd[1]: authelia.service: Failed with result 'exit-code'.
Jul 14 07:24:07 authelia systemd[1]: authelia.service: Consumed 3min 46.128s CPU time.
Jul 14 07:43:48 authelia systemd[1]: Started Authelia authentication and authorization server.
Jul 14 07:43:48 authelia authelia[30735]: time="2023-07-14T07:43:48Z" level=info msg="Authelia v4.37.5 is starting"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Fixed in 0bb657e11cfa6b9f16cd28340291b121fa1579bc
