### ISSUE TITLE
SMTP runtime error

### ISSUE THREAD

**Issue by adriaanh** [authelia/authelia#626]
Hi all,

I get a weird error with the SMTP notifier. Was using Gmail before this, which was working fine, but with my custom domain mail address this is no longer working. I'm using transip for sending the mail. They are not using STARTTLS over port 587, but rather using SSL over port 465 (I think this is 'normal' TLS?, but I'm no expert in this matter). Refer to the settings (in Dutch, sorry): https://www.transip.nl/knowledgebase/artikel/309-algemene-instellingen-voor-mijn-e-mailadres/

While looking at the code, I should have debug messages regarding failed authentication or otherwise, but I'm rather getting a runtime error and, as it seems, a restart of Authelia. Below is my redacted config and log. 

What I already tried:
* `disable_require_tls = true`, but this provides me with the same error. 
* Tried on two different hosts, but the same errors
* Validating the settings with Outlook, but Outlook is sending mails just fine. 

SMTP config:
```
  smtp:
    username: mail@example.com
    password: password
    host: smtp.transip.email
    port: 465
    sender: mail@example.com
```

Logs:
```
authelia    | time="2020-02-06T17:54:13+01:00" level=info msg="Logging severity set to debug"
authelia    | time="2020-02-06T17:54:13+01:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
authelia    | Selected public_html directory is  ./public_html
authelia    | time="2020-02-06T17:54:13+01:00" level=info msg="Authelia is listening on 0.0.0.0:9091"
authelia    | time="2020-02-06T17:54:20+01:00" level=debug msg="Sending an email to user X (mail@example.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip=X
authelia    | time="2020-02-06T17:54:20+01:00" level=debug msg="Notifier SMTP client attempting connection to smtp.transip.email:465"
authelia    | panic: runtime error: invalid memory address or nil pointer dereference
authelia    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb84bc6]
authelia    | 
authelia    | goroutine 24 [running]:
authelia    | net/smtp.(*Client).Close(...)
authelia    |   net/smtp/smtp.go:76
authelia    | github.com/authelia/authelia/internal/notification.(*SMTPNotifier).Send(0xc0002c0600, 0xc0004d3d40, 0x18, 0xe2c175, 0x1f, 0xc000784000, 0x39b8, 0xc000010050, 0xc0000e0000)
authelia    |   github.com/authelia/authelia@/internal/notification/smtp_notifier.go:215 +0x546
authelia    | github.com/authelia/authelia/internal/middlewares.IdentityVerificationStart.func1(0xc0001d3080)
authelia    |   github.com/authelia/authelia@/internal/middlewares/identity_verification.go:70 +0xa13
authelia    | github.com/authelia/authelia/internal/middlewares.RequireFirstFactor.func1(0xc0001d3080)
authelia    |   github.com/authelia/authelia@/internal/middlewares/require_first_factor.go:14 +0xab
authelia    | github.com/authelia/authelia/internal/middlewares.AutheliaMiddleware.func1.1(0xc0000e0000)
authelia    |   github.com/authelia/authelia@/internal/middlewares/authelia_context.go:46 +0x180
authelia    | github.com/fasthttp/router.(*Router).Handler(0xc0005abae0, 0xc0000e0000)
authelia    |   github.com/fasthttp/router@v0.5.2/router.go:326 +0xfb3
authelia    | github.com/authelia/authelia/internal/middlewares.LogRequestMiddleware.func1(0xc0000e0000)
authelia    |   github.com/authelia/authelia@/internal/middlewares/log_request.go:14 +0x108
authelia    | github.com/valyala/fasthttp.(*Server).serveConn(0xc000120000, 0xffb620, 0xc000010400, 0x0, 0x0)
authelia    |   github.com/valyala/fasthttp@v1.6.0/server.go:2018 +0x6ab
authelia    | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0005a8d20, 0xc0004ca180)
authelia    |   github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 +0xc0
authelia    | github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0005a8d20, 0xc0004ca180, 0xcc72e0, 0xc0004ca180)
authelia    |   github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 +0x35
authelia    | created by github.com/valyala/fasthttp.(*workerPool).getCh
authelia    |   github.com/valyala/fasthttp@v1.6.0/workerpool.go:194 +0x101
authelia    | time="2020-02-06T17:55:22+01:00" level=info msg="Logging severity set to debug"
authelia    | time="2020-02-06T17:55:22+01:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
```

**Comment by james-d-elliott** [comment]
Authelia currently doesn't support SMTPS, does your email server have submission 587 or plain SMTP with STARTTLS 25?

**Comment by adriaanh** [comment]
Oh ok, that clears thing up, thanks! Would be good if there is an error message at least. Both port 25 and 587 are not used by the provider. When tested, I got the same error message by the way. Seems that when no valid connection could be made, it is a runtime error. 

Yes, I use docker deployment. Think I will switch from mail provider for the short term. Tanks anyway!

**Comment by james-d-elliott** [comment]
@adriaanh here is a test docker image you can use:

[authelia/authelia:feature-smtps-support](https://hub.docker.com/layers/authelia/authelia/feature-smtps-support/images/sha256-a75037e066fc681db52325ce6e2657e2b7f2bbe8a7532c2dc37247de82cdb8d9)

**Comment by adriaanh** [comment]
Wow, thanks. Will test this weekend!

**Comment by adriaanh** [comment]
Tested it today and it worked well! Don't know if it is the mail provider or Authelia, but there is a significant delay between attempting to connect and actually connecting. Tried with another host and the same thing. Might this have to do with configuration of Authelia, or is it just my mail provider?

Config:
```
  smtp:
    username: mail@example.com
    password: password
    sender: mail@example.com
    host: smtp.transip.email
    port: 465
    port_tls: true
```

Logs:
```
authelia    | time="2020-02-08T09:41:11+01:00" level=debug msg="Notifier SMTP client attempting connection to smtp.transip.email:465"
authelia    | time="2020-02-08T09:41:18+01:00" level=debug msg="Notifier SMTP client connected successfully"
authelia    | time="2020-02-08T09:41:18+01:00" level=debug msg="Notifier SMTP connection is already encrypted, skipping STARTTLS"
authelia    | time="2020-02-08T09:41:18+01:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
authelia    | time="2020-02-08T09:41:18+01:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
authelia    | time="2020-02-08T09:41:18+01:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
authelia    | time="2020-02-08T09:41:18+01:00" level=debug msg="Notifier SMTP client attempting to send email body to mail@example.com"
authelia    | time="2020-02-08T09:41:21+01:00" level=debug msg="Notifier SMTP client successfully sent email"
```

**Comment by james-d-elliott** [comment]
That sounds like a provider thing, but I can check sometime tomorrow.

**Comment by james-d-elliott** [comment]
It's a provider issue, there is no such timeout in any of the tests I did.
