### ISSUE TITLE
AUTHELIA_SESSION_REDIS_PASSWORD : Err invalid password

### ISSUE THREAD

**Issue by davama** [authelia/authelia#632]
Hello,

was testing the env settings.
So far working running:
```
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD="<strng>"
AUTHELIA_SESSION_SECRET="<some-string>"
```

Then on `config.yml` i comment out the `password:`/`secret` line in the `ldap` and `session` context.

Was testing the REDIS env variable and got this error when running on the terminal

```
[root@authelia authelia]# pwd
/opt/authelia
[root@authelia authelia]# ls
authelia-linux-amd64.tar.gz  authelia.service  config.template.yml  public_html
[root@authelia authelia]# /usr/local/sbin/authelia --config /etc/authelia/config.yml
INFO[0000] Logging severity set to debug                
DEBU[0000] Notifier SMTP client initializing TLS configuration 
panic: Redis connection error: ERR invalid password

goroutine 1 [running]:
github.com/authelia/authelia/internal/session.NewProvider(0xc00029bc10, 0x10, 0xc000028018, 0x22, 0x15180, 0xe10, 0xc00029bc60, 0xc, 0xc00038a030, 0x0)
	github.com/authelia/authelia@/internal/session/provider.go:25 +0x161
main.startServer()
	github.com/authelia/authelia@/cmd/authelia/main.go:91 +0x48c
main.main.func1(0xc000241680, 0xc000323020, 0x0, 0x2)
	github.com/authelia/authelia@/cmd/authelia/main.go:109 +0x20
github.com/spf13/cobra.(*Command).execute(0xc000241680, 0xc0000a4160, 0x2, 0x2, 0xc000241680, 0xc0000a4160)
	github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000241680, 0xc000187f38, 0x3, 0x3)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	github.com/authelia/authelia@/cmd/authelia/main.go:124 +0x186
``` 

And yes, my env are there:

```
$ env | grep AUTH | cut -d'=' -f1
AUTHELIA_SESSION_SECRET
AUTHELIA_SESSION_REDIS_PASSWORD
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
```

And password for redis is correct:

```
[root@authelia authelia]# redis-cli -a authelia FLUSHALL
OK
```

Once i unset my variable and uncomment the password line in the redis context, it works:

```
[root@authelia authelia]# unset AUTHELIA_SESSION_REDIS_PASSWORD
[root@authelia authelia]# /usr/local/sbin/authelia --config /etc/authelia/config.yml
INFO[0000] Logging severity set to debug                
DEBU[0000] Notifier SMTP client initializing TLS configuration 
Selected public_html directory is  ./public_html
INFO[0000] Authelia is listening on 127.0.0.1:9091      
``` 

Hope thats enough info!
Thank you for the support

-Dave

**Comment by davama** [comment]
One more note:

It does work with systemd:

```
[root@authelia authelia]# systemctl cat authelia
# /usr/lib/systemd/system/authelia.service
[Unit]
Description=2FA Single Sign-On Authentication Server
Requires=mariadb.service redis.service
After=network.target

[Service]
EnvironmentFile=/etc/sysconfig/authelia
User=authelia
Group=authelia
WorkingDirectory=/opt/authelia
ExecStart=/usr/local/sbin/authelia --config /etc/authelia/config.yml

[Install]
WantedBy=multi-user.target
```

Inside the `/etc/sysconfig/authelia` file i have my variables defined, including the REDIS one...

So it does not work running in the shell.

**Comment by james-d-elliott** [comment]
Try this:
```
export AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD="<strng>"
export AUTHELIA_SESSION_SECRET="<some-string>"
```

**Comment by clems4ever** [comment]
@davama , just to be sure, do you have special characters in your secret/password? It should work but special chars are not tested in integration so it might be an issue with cobra.
Is it easy for you to try without special chars?

**Comment by davama** [comment]
Found the issue.

Not a bug.
Had to do with how my env variables were being exported. 

Looks like they were being exported as: (with the literal `"` characters...)
```
VAR="blabal"
```

instead of:
```
VAR=blabla
```

Thanks!!
