### ISSUE TITLE
crash if no mail attribute found in ldap

### ISSUE THREAD

**Issue by jcollie** [authelia/authelia#647]
v4.4.0 crashes ii the LDAP user does not have a mail attribute. I realize that this is a configuration error on my part, but I think that authelia shouldn't crash and should log a more informative error to help troubleshoot the problem.

```
# jeff, users, ocjtech.us
dn: cn=jeff,ou=users,dc=ocjtech,dc=us
givenName: Jeffrey
sn: Ollie
cn: jeff
uid: jeff
uidNumber: 1000
gidNumber: 1000
homeDirectory: /home/users/jeff
loginShell: /bin/sh
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: top
userPassword:: xxxxxxx
```

```
time="2020-02-22T01:22:41Z" level=info msg="Logging severity set to debug"
time="2020-02-22T01:22:41Z" level=debug msg="Notifier SMTP client initializing TLS configuration"
Selected public_html directory is  ./public_html
time="2020-02-22T01:22:41Z" level=info msg="Authelia is listening on 0.0.0.0:9091"
time="2020-02-22T01:23:22Z" level=debug msg="LDAP client starts a session over raw TCP"
time="2020-02-22T01:23:22Z" level=debug msg="LDAP client starts a session over raw TCP"
time="2020-02-22T01:23:22Z" level=debug msg="LDAP client starts a session over raw TCP"
time="2020-02-22T01:23:22Z" level=debug msg="Credentials validation of user jeff is ok" method=POST path=/api/firstfactor remote_ip=192.168.4.1
time="2020-02-22T01:23:22Z" level=debug msg="Mark authentication attempt made by user jeff" method=POST path=/api/firstfactor remote_ip=192.168.4.1
time="2020-02-22T01:23:22Z" level=debug msg="LDAP client starts a session over raw TCP"
time="2020-02-22T01:23:22Z" level=debug msg="LDAP client starts a session over raw TCP"
time="2020-02-22T01:23:22Z" level=debug msg="LDAP client starts a session over raw TCP"
panic: runtime error: index out of range [0] with length 0

goroutine 32 [running]:
github.com/authelia/authelia/internal/authentication.(*LDAPUserProvider).GetDetails(0xc00038b200, 0xc000183208, 0x4, 0x0, 0x0, 0x0)
	github.com/authelia/authelia@/internal/authentication/ldap_user_provider.go:244 +0xd71
github.com/authelia/authelia/internal/handlers.FirstFactorPost(0xc0004e9500)
	github.com/authelia/authelia@/internal/handlers/handler_firstfactor.go:87 +0x82b
github.com/authelia/authelia/internal/middlewares.AutheliaMiddleware.func1.1(0xc0000cea00)
	github.com/authelia/authelia@/internal/middlewares/authelia_context.go:46 +0x180
github.com/fasthttp/router.(*Router).Handler(0xc0003c20f0, 0xc0000cea00)
	github.com/fasthttp/router@v0.5.2/router.go:326 +0xfb3
github.com/authelia/authelia/internal/middlewares.LogRequestMiddleware.func1(0xc0000cea00)
	github.com/authelia/authelia@/internal/middlewares/log_request.go:14 +0x110
github.com/valyala/fasthttp.(*Server).serveConn(0xc00041c000, 0xffd400, 0xc0002f21d8, 0x0, 0x0)
	github.com/valyala/fasthttp@v1.6.0/server.go:2018 +0x6ab
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000281c20, 0xc0001af960)
	github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000281c20, 0xc0001af960, 0xcc8380, 0xc0001af960)
	github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	github.com/valyala/fasthttp@v1.6.0/workerpool.go:194 +0x101
```

**Comment by james-d-elliott** [comment]
Thanks for reporting @jcollie should be an easy fix. You are correct that it should not happen.

**Comment by nightah** [comment]
@jcollie do you mind trying `docker pull authelia/authelia:fix-crash-on-missing-mail` If you still happen to have misconfigured users?
